Añadir configuración de CircleCI para pipeline

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -14,6 +14,14 @@ jobs:
       - setup_remote_docker:
           docker_layer_caching: true  # Caching de capas Docker para optimizar tiempos
       - run:
+          name: Verificar MY_ENV_VAR
+          command: |
+            echo "MY_ENV_VAR: $MY_ENV_VAR"
+            if [ -z "$MY_ENV_VAR" ]; then
+              echo "Error: MY_ENV_VAR no está definida"
+              exit 1
+            fi
+      - run:
           name: Instalar dependencias
           command: |
             python3 -m venv venv  # Crear entorno virtual
@@ -45,13 +53,13 @@ jobs:
       - run:
           name: Verificar variables de entorno para Docker
           command: |
+            echo "DOCKERHUB_USER: $DOCKERHUB_USER"
+            echo "IMAGE_NAME: $IMAGE_NAME"
+            echo "CIRCLE_SHA1: $CIRCLE_SHA1"
             if [ -z "$DOCKERHUB_USER" ] || [ -z "$IMAGE_NAME" ] || [ -z "$CIRCLE_SHA1" ]; then
               echo "Error: Una o más variables están vacías. DOCKERHUB_USER=$DOCKERHUB_USER IMAGE_NAME=$IMAGE_NAME CIRCLE_SHA1=$CIRCLE_SHA1"
               exit 1
             fi
-            echo "DOCKERHUB_USER: $DOCKERHUB_USER"
-            echo "IMAGE_NAME: $IMAGE_NAME"
-            echo "CIRCLE_SHA1: $CIRCLE_SHA1"
       - run:
           name: Construir imagen Docker
           command: |
